/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CWApos3Xks7
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Card, CardTitle, CardHeader, CardContent } from "@/components/ui/card";

export function LandingPage() {
  return (
    <div className="bg-white dark:bg-gray-950 text-gray-900 dark:text-gray-50">
      <header className="bg-white dark:bg-gray-950 shadow">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
          <div className="flex items-center">
            <h1 className="text-2xl font-bold">A to Z Massage</h1>
          </div>
          <nav className="hidden md:flex space-x-4">
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Home
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              About
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Services
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Contact Us
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              <FacebookIcon className="w-6 h-6" />
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              <TwitterIcon className="w-6 h-6" />
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              <YoutubeIcon className="w-6 h-6" />
            </Link>
          </div>
        </div>
      </header>
      <main>
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16 lg:py-20">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="hidden md:block order-2">
              <iframe
                src="https://www.youtube.com/embed/nOxB9b3jGpQ"
                allowFullScreen={true}
                className="w-full h-80 lg:h-full"
              ></iframe>
            </div>
            <div className="order-1 space-y-4">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold">
                  Welcome to A to Z Massage
                </h2>
                <p className="text-gray-700 dark:text-gray-400">
                  {`Massage is not just a luxury, it's a key piece of your health
                  and wellness plan. With each scheduled service, you gain a
                  partner in health and total relief! Experience the perfect
                  care that's right for you - perfectly tailored to your own
                  health and wellness needs that will leave you ready to work
                  and play. Our highly skilled massage therapists will be happy
                  to work with you to help you select the services that best
                  meets your needs.`}
                </p>
                <p className="text-gray-700 dark:text-gray-400">
                  A routine of regular massage therapy can help keep
                  long-lasting health benefits - reduced anxiety, enhanced
                  calmness, restful sleep, lower blood pressure, immune system
                  regulation, migraine relief, and an overall sense of peace and
                  relaxation. Massage is genuinely life-changing and
                  complementary and integrative medicine is increasingly being
                  offered along with standard treatment for a wide range of
                  medical conditions and situations.
                </p>
              </div>
              <Button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                SCHEDULE APPOINTMENT
              </Button>
            </div>
          </div>
        </section>
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16 lg:py-20">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <Card className="hidden md:block col-span-1">
              <Image
                alt="Massage session"
                className="rounded-lg"
                height="300"
                src="/banner.jpg"
                style={{
                  objectFit: "cover",
                }}
                width="800"
              />
            </Card>
            <div className="grid grid-cols-2 gap-4">
              <Card className="col-span-1">
                <Image
                  alt="Sports Massage"
                  className="rounded-full"
                  height="100"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width="100"
                />
                <CardTitle>Sports Massage</CardTitle>
              </Card>
              <Card className="col-span-1">
                <Image
                  alt="Performance Recovery"
                  className="rounded-full"
                  height="100"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width="100"
                />
                <CardTitle>Performance Recovery</CardTitle>
              </Card>
              <Card className="col-span-1">
                <Image
                  alt="Relaxation Massage"
                  className="rounded-full"
                  height="100"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width="100"
                />
                <CardTitle>Relaxation Massage</CardTitle>
              </Card>
              <Card className="col-span-1">
                <Image
                  alt="Infrared Sauna"
                  className="rounded-full"
                  height="100"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width="100"
                />
                <CardTitle>Infrared Sauna</CardTitle>
              </Card>
            </div>
            <Button className="col-span-2 md:col-span-1 lg:col-span-1 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
              VIEW MORE SERVICES
            </Button>
          </div>
        </section>
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16 lg:py-20">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <Card className="col-span-1">
              <CardHeader className="border-b p-4">
                <CardTitle className="text-lg font-bold">PROMOTIONS</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <img
                    alt="First Visit Sports Massage"
                    className="rounded-lg"
                    height="60"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/60",
                      objectFit: "cover",
                    }}
                    width="100"
                  />
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    $45 FIRST VISIT SPORTS MASSAGE
                  </p>
                </div>
                <div className="space-y-2">
                  <img
                    alt="Infrared Sauna Packages"
                    className="rounded-lg"
                    height="60"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/60",
                      objectFit: "cover",
                    }}
                    width="100"
                  />
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    INFRARED SAUNA PACKAGES STARTING AT $20
                  </p>
                </div>
                <div className="space-y-2">
                  <img
                    alt="Infrared Sauna Plus Massage Session"
                    className="rounded-lg"
                    height="60"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/60",
                      objectFit: "cover",
                    }}
                    width="100"
                  />
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    INFRARED SAUNA PLUS MASSAGE SESSION FOR ONLY $60
                  </p>
                </div>
              </CardContent>
            </Card>
            <Card className="col-span-2">
              <CardHeader className="border-b p-4">
                <CardTitle className="text-lg font-bold">REVIEWS</CardTitle>
              </CardHeader>
              <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="border p-4 rounded-lg">
                  <div className="flex items-center mb-2">
                    <StarIcon className="text-red-500" />
                    <p className="ml-2 text-sm text-gray-500 dark:text-gray-400">
                      5.0
                    </p>
                  </div>
                  <p className="text-sm text-gray-700 dark:text-gray-400">
                    "Dave is amazing! He has a great understanding of the body
                    and is genuinely concerned to help me. I can see him with
                    total peace."
                  </p>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-4">
                    - Customer's Name
                  </p>
                </div>
                <div className="border p-4 rounded-lg">
                  <div className="flex items-center mb-2">
                    <StarIcon className="text-red-500" />
                    <p className="ml-2 text-sm text-gray-500 dark:text-gray-400">
                      5.0
                    </p>
                  </div>
                  <p className="text-sm text-gray-700 dark:text-gray-400">
                    "This service was exactly what I am looking for my recovery
                    phase. Booking and payment system was so slick! I found them
                    because of my..."
                  </p>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-4">
                    - Customer's Name
                  </p>
                </div>
                <div className="border p-4 rounded-lg">
                  <div className="flex items-center mb-2">
                    <StarIcon className="text-red-500" />
                    <p className="ml-2 text-sm text-gray-500 dark:text-gray-400">
                      5.0
                    </p>
                  </div>
                  <p className="text-sm text-gray-700 dark:text-gray-400">
                    "So glad to have finally found a staff that pushes me down
                    and around to give me a very best my first..."
                  </p>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-4">
                    - Customer's Name
                  </p>
                </div>
                <Button className="col-span-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                  READ MORE REVIEWS
                </Button>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <footer className="bg-white dark:bg-gray-950 border-t">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 flex justify-between items-center">
          <div>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              A to Z Massage
            </p>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              4000 Central Florida Blvd, Orlando, FL 32816
            </p>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Phone: 813-555-0100
            </p>
          </div>
          <div>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              FOLLOW ON SOCIAL MEDIA
            </p>
            <div className="flex space-x-2 mt-1">
              <Link
                className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <FacebookIcon className="w-6 h-6" />
              </Link>
              <Link
                className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <TwitterIcon className="w-6 h-6" />
              </Link>
              <Link
                className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                <YoutubeIcon className="w-6 h-6" />
              </Link>
            </div>
          </div>
        </div>
        <p className="text-xs text-center text-gray-500 dark:text-gray-400 mt-6">
          © 2023 A to Z Massage. All rights reserved.
        </p>
      </footer>
    </div>
  );
}

function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  );
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}

function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}

function YoutubeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  );
}
